import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } from 'docx';
import { saveAs } from 'file-saver';
import { BookProject } from '../types';

function stripLeadingTitle(content: string, title: string): string {
  const lines = content.split('\n');
  const titleLower = title.toLowerCase().replace(/[^a-z0-9]/g, '');

  let startIndex = 0;
  for (let i = 0; i < Math.min(lines.length, 5); i++) {
    const lineCleaned = lines[i].trim().replace(/^#+\s*/, '').replace(/\*\*/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');
    if (!lineCleaned) {
      startIndex = i + 1;
      continue;
    }
    if (lineCleaned.includes(titleLower) || titleLower.includes(lineCleaned)) {
      startIndex = i + 1;
      while (startIndex < lines.length && lines[startIndex].trim() === '') {
        startIndex++;
      }
      break;
    }
    break;
  }

  return lines.slice(startIndex).join('\n').trim();
}

export async function generatePDF(project: BookProject): Promise<void> {
  const pdf = new jsPDF();
  let yPosition = 20;
  
  // Title page
  pdf.setFontSize(24);
  pdf.text('Generated by Author AI', 20, yPosition);
  yPosition += 20;
  
  pdf.setFontSize(16);
  pdf.text(`Book Type: ${project.idea.type}`, 20, yPosition);
  yPosition += 10;
  pdf.text(`Language: ${project.idea.language}`, 20, yPosition);
  yPosition += 20;
  
  pdf.setFontSize(14);
  const ideaLines = pdf.splitTextToSize(`Idea: ${project.idea.idea}`, 170);
  pdf.text(ideaLines, 20, yPosition);
  yPosition += ideaLines.length * 7 + 20;

  // Chapters
  project.outlines.forEach((chapter, index) => {
    if (yPosition > 250) {
      pdf.addPage();
      yPosition = 20;
    }
    
    pdf.setFontSize(18);
    const titleLines = pdf.splitTextToSize(chapter.title, 170);
    titleLines.forEach((line: string) => {
      if (yPosition > 270) {
        pdf.addPage();
        yPosition = 20;
      }
      pdf.text(line, 20, yPosition);
      yPosition += 10;
    });
    yPosition += 5;
    
    if (chapter.content) {
      pdf.setFontSize(12);
      const cleanedContent = stripLeadingTitle(chapter.content, chapter.title);
      const contentLines = pdf.splitTextToSize(cleanedContent, 170);
      
      contentLines.forEach((line: string) => {
        if (yPosition > 280) {
          pdf.addPage();
          yPosition = 20;
        }
        pdf.text(line, 20, yPosition);
        yPosition += 7;
      });
    }
    
    yPosition += 15;
  });

  pdf.save(`${project.idea.idea.substring(0, 30)}_book.pdf`);
}

export async function generateWord(project: BookProject): Promise<void> {
  try {
    // Create document sections
    const sections = [];
    
    // Title page
    sections.push(
      new Paragraph({
        children: [new TextRun({ text: "Generated by Author AI", bold: true, size: 32 })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      })
    );
    
    sections.push(
      new Paragraph({
        children: [new TextRun({ text: project.idea.idea, bold: true, size: 24 })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 300 },
      })
    );
    
    sections.push(
      new Paragraph({
        children: [new TextRun({ text: `Type: ${project.idea.type} | Language: ${project.idea.language}`, size: 16 })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      })
    );
    
    // Table of Contents
    sections.push(
      new Paragraph({
        children: [new TextRun({ text: "Table of Contents", bold: true, size: 20 })],
        spacing: { before: 400, after: 200 },
      })
    );
    
    project.outlines.forEach((chapter, index) => {
      sections.push(
        new Paragraph({
          children: [new TextRun({ text: `${index + 1}. ${chapter.title}` })],
          spacing: { after: 100 },
        })
      );
    });
    
    // Chapters
    project.outlines.forEach((chapter) => {
      sections.push(
        new Paragraph({
          children: [new TextRun({ text: chapter.title, bold: true, size: 18 })],
          spacing: { before: 400, after: 200 },
        })
      );
      
      if (chapter.content) {
        const cleanedContent = stripLeadingTitle(chapter.content, chapter.title);
        const paragraphs = cleanedContent.split('\n').filter(p => p.trim());
        paragraphs.forEach((paragraph) => {
          sections.push(
            new Paragraph({
              children: [new TextRun({ text: paragraph.trim() })],
              spacing: { after: 200 },
            })
          );
        });
      }
    });

    const doc = new Document({
      sections: [
        {
          children: sections,
        },
      ],
    });

    const blob = await Packer.toBlob(doc);
    
    const cleanTitle = project.idea.idea.replace(/[^a-zA-Z0-9\s]/g, '').replace(/\s+/g, '_').substring(0, 30);
    
    saveAs(blob, `${cleanTitle || 'Book'}_AuthorAI.docx`);
  } catch (error) {
    console.error('Error generating Word document:', error);
    throw new Error(`Failed to generate Word document: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}